add view download status group

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,10 +27,28 @@ jobs:
         mkdir -p ./CI/{spotify,apple_music,deezer}/{track,album,artist,playlist}
 
         cat << EOF > ./CI/prep.sh
+          RG_SRC="\$(which rg)"
+          rg() {
+            printf "rg: pattern: /\$@/" > /dev/stderr
+            \$RG_SRC --fixed-strings --passthru "\$@"
+            if [[ \$? == 0 ]]; then
+              echo " (matched)" > /dev/stderr
+            else
+              echo " (failed to match)" > /dev/stderr
+              return 1
+            fi
+          }
+
           freyr() {
             echo "::group::[\$attempts/3] Downloading..."
             script -qfc "freyr \$@" /dev/null | tee .freyr_log
             echo "::endgroup::"
+            i=\$(cat .freyr_log | \$RG_SRC -n '.' | \$RG_SRC --fixed-strings '[•] Embedding Metadata' | cut -d':' -f1)
+            if [[ \$i ]]; then
+              echo "::group::[\$attempts/3] View Download Status"
+              cat .freyr_log | tail +\$i
+              echo "::endgroup::"
+            fi
           }
 
           exec_retry() {
@@ -50,18 +68,6 @@ jobs:
             STAGE=\$(realpath --relative-to=../.. .) && cd ../..
             tree -sh \$STAGE
             echo "::endgroup::"
-          }
-
-          RG_SRC="\$(which rg)"
-          rg() {
-            printf "rg: pattern: /\$@/" > /dev/stderr
-            \$RG_SRC --fixed-strings --passthru "\$@"
-            if [[ \$? == 0 ]]; then
-              echo " (matched)" > /dev/stderr
-            else
-              echo " (failed to match)" > /dev/stderr
-              return 1
-            fi
           }
 
           validate() {
